### ISSUE TITLE
vue3.x初始化的项目安装lint命令之后启动项目报错（不含任何的eslint）

### ISSUE THREAD

**Issue by zhanyi233** [cool-fe/winex-cli#26]
![image](https://user-images.githubusercontent.com/37531008/119429858-4c44ca80-bd42-11eb-97bf-71d5202076cd.png)

**Comment by GGwujun** [comment]
@winex-fe @zhanyi233 块复现下，最新版还有问题没？

**Comment by GGwujun** [comment]
@GGwujun @zhanyi233 @icemirror @winex-fe @frontHu 

如何处理vue-cli创建的项目生成的eslint配置和lint生成的eslint配置，在做配置合并的时候我建议如下操作：

1. 肯定是先以vue-cli/winex init创建项目，然后才会使用winex lint，那么我们首先合并eslintConfig配置到.eslintrc.js
2. 要不要删除package.json中的eslintConfig？
3. 要不要删除"@vue/cli-plugin-eslint": "~4.5.0"插件？（此插件是vue-cli-service启动项目和build项目做eslint校验的插件）
4. 要不要删除vue-cli默认安装的yorkie（我们现在git hook检测是采用的lint-staged）

如果以后卫宁的所有项目初始化不允许采用vue-cli，全部采用winex init，那么如上的问题都没有。

**Comment by zhanyi233** [comment]
没有问题了

**Comment by GGwujun** [comment]
#61
