### ISSUE TITLE
项目中没有eslint配置，也会被检测出来含有配置；另外还有报错：extends

### ISSUE THREAD

**Issue by zhanyi233** [cool-fe/winex-cli#28]
![image](https://user-images.githubusercontent.com/37531008/119432698-60d79180-bd47-11eb-8b03-320c907e61e7.png)
![image](https://user-images.githubusercontent.com/37531008/119432710-63d28200-bd47-11eb-9b25-4ae77ce4c312.png)

**Comment by GGwujun** [comment]
fixed. #29
