### ISSUE TITLE
项目的changelog生成内容不对

### ISSUE THREAD

**Issue by GGwujun** [cool-fe/winex-cli#33]
![image](https://user-images.githubusercontent.com/17949342/119474900-36a1c600-bd7f-11eb-953f-31fd69c6f99b.png)

**Comment by icemirror** [comment]
## 基本用法
lerna-changelog是针对pr提交时的tag进行整理汇总成CHANGELOG.md文件的. 因此提pr时的commit规范就尤其重要, 必须按照一定的规则进行.

## 提pr流程
- 从main分支切换出feat-xxx, bug-xxx等分支;
- 完成开发后进行commit，将新分支push到remote端;
- 创建pr，并打上label，此处一定要打上label, 注意label一定要跟changelog配置的label保持一致;
- 切记要在merge之前打上label;
- 进行merge pr操作;
- 本地切换到main分支并进行pull操作;
- npm run changlog, 即可

## 自定义label
自定义情况下, 需要在package.json文件中配置changelogConfig:
```
"changelog": {
    "repo": "cool-fe/winex-cli",
    "labels": {
      "feat": ":rocket: New Feature",
      "bug": ":bug: Bug Fix",
      "doc": ":memo: Documentation",
      ...
    }
  }
```
![image](https://user-images.githubusercontent.com/14882452/119611611-82ab4400-be2d-11eb-8e5d-e6e22d678f5e.png)
![image](https://user-images.githubusercontent.com/14882452/119610829-6d81e580-be2c-11eb-84db-5d78af4b8a98.png)

## 默认label
默认情况下, 不需要在package.json中进行changelog配置, lerna会根据以下label进行changlog生成:
```
breaking (:boom: Breaking Change)
enhancement (:rocket: Enhancement)
bug (:bug: Bug Fix)
documentation (:memo: Documentation)
internal (:house: Internal)
```
![image](https://user-images.githubusercontent.com/14882452/119611444-4a0b6a80-be2d-11eb-812a-71bb179bb9cb.png)
![image](https://user-images.githubusercontent.com/14882452/119611536-68716600-be2d-11eb-8c4c-d6fa4d5182b5.png)

## 结论
在之前的开发流程中, 添加changlog自定义label配置(如需要), 提pr时或merge pr之前一定要为pr添加label, 以达到顺利生成CHANGELOG.md的目的.

## 参考文章
- [lerna-changelog readme](https://yarnpkg.com/package/lerna-changelog)
- [lerna多包存储库实战](https://github.com/qinzhiwei1993/lerna-changelog)
- [lerna的使用入门](https://juejin.cn/post/6844903789749600269)
